server:
  port: 18080

spring:
    profiles:
        active: dev
    mail:
        host: smtp.gmail.com
        port: 587
        username: bupurashok@gmail.com
        password: bqoxbykisfwfbrkj
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com       